In [5]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [3]:
os.chdir(r'G:\공유 드라이브\SicParvisMagna\데이터\코로나_매출')
df_covid = pd.read_csv('대구구별_확진자수_21-01-02~21-07-20.csv')
df_covid

     Unnamed: 0  수성  달서   북  서  중  남  달성  동
0    2021-01-02  13   5   4  5  0  2   2  2
1    2021-01-03   7   6   1  6  1  2   1  2
2    2021-01-04  12   5   3  0  1  1   0  7
3    2021-01-05  21   3   1  0  0  0   1  5
4    2021-01-06  10   4   1  4  1  1   0  2
..          ...  ..  ..  .. .. .. ..  .. ..
195  2021-07-16  13   5   3  2  1  1   1  4
196  2021-07-17   3   6   2  4  4  3   2  4
197  2021-07-18  11  12  10  2  2  1   1  2
198  2021-07-19   2   4  10  4  4  5   0  2
199  2021-07-20   5   7   9  1  2  2   0  2

[200 rows x 9 columns]

In [4]:
df_sales = pd.read_csv('일별매출_2021-01-02~2021-07-20.csv')
df_sales

,Unnamed: 0,남김천휴게소(무보까국밥),무보까국밥(구평점),무보까국밥(상인점),무보까국밥(서구점),무보까국밥(서문점),무보까국밥(석적점),무보까국밥(성서점),무보까국밥(신평점),무보까국밥(안동점),무보까국밥(엑스코점),무보까국밥(옥계점),무보까국밥(용산점),무보까국밥(원대점),무보까국밥(장기점),무보까국밥(평리점),무보까국밥(황상점),무보까국밥과보쌈(신서점)
0,2021-01-02,0,"697,000","860,000","517,500","140,000","1,649,000","2,234,500","546,500","614,000","52,500","1,389,500","862,500","244,000","625,000","895,000","468,000","1,173,000"
1,2021-01-03,0,"684,500","874,500","1,039,500","67,500","1,581,000","2,287,000","335,500",0,"151,500","1,256,500","912,000","133,500","842,000","952,500","555,500","1,503,000"
2,2021-01-04,"93,000","581,500","712,500","736,000","277,500","1,623,500","1,715,500",0,"1,160,000","266,000","976,000","473,500","284,000","501,500","940,500","637,000","1,247,000"
3,2021-01-05,"100,000","809,000","900,500","618,500","309,500","1,349,500","1,840,000","808,000","673,500","174,500","858,000","745,000","346,500","710,500","446,000","380,000","1,047,000"
4,2021-01-06,"30,000","1,025,500","787,000","383,000","135,000","1,316,500","1,612,000",0,"755,000","111,000","1,197,500","456,000","89,000","652,500","835,500","375,000","1,351,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2021-07-16,"38,500","1,286,500","922,500","417,000","122,000","2,340,000","1,647,000","541,500","498,500","361,000","2,198,000","501,000","244,500","850,500",0,"524,500","1,045,000"
196,2021-07-17,"37,500","1,431,000","1,174,000","417,500","80,000","3,173,500","3,041,500","447,500",0,"688,000","2,830,000","481,500","276,000","1,065,000",0,"562,000","1,396,000"
197,2021-07-18,0,"1,355,000","1,432,500","799,000","154,500","1,702,000","3,012,000","759,000",0,"343,500","1,686,500","801,000","217,500","1,080,500",0,"836,500","1,550,000"
198,2021-07-19,"102,000","1,322,500","783,000","386,000","435,500","2,161,500","1,858,000","359,500","450,000","45,500","1,902,000","878,500","130,000","608,000",0,"516,000","1,116,000"
199,2021-07-20,"49,000","1,149,000","804,500","453,500","256,500","2,204,000","1,510,000","302,000","524,500","277,000","1,990,500","520,000","105,000","679,000",0,"398,500","1,266,200"

## 달서구 확진자 수 VS 장기점 매출

In [62]:
dalseo_jangki = pd.DataFrame()
dalseo_jangki['covid_dalseo'] = df_covid['달서']
dalseo_jangki['sales_jangki'] = [int(a.replace(',', '')) for a in df_sales['무보까국밥(장기점)']]
dalseo_jangki

     covid_dalseo  sales_jangki
0               5        625000
1               6        842000
2               5        501500
3               3        710500
4               4        652500
..            ...           ...
195             5        850500
196             6       1065000
197            12       1080500
198             4        608000
199             7        679000

[200 rows x 2 columns]

In [104]:
scaler = StandardScaler()
dalseo_jangki_sc = scaler.fit_transform(dalseo_jangki)
dalseo_jangki_sc = pd.DataFrame(dalseo_jangki_sc)
dalseo_jangki_sc.columns = ('covid_dalseo', 'sales_jangki')
dalseo_jangki_sc

     covid_dalseo  sales_jangki
0        0.385001     -1.087705
1        0.656128     -0.491887
2        0.385001     -1.426800
3       -0.157254     -0.852947
4        0.113873     -1.012198
..            ...           ...
195      0.385001     -0.468548
196      0.656128      0.120406
197      2.282891      0.162965
198      0.113873     -1.134382
199      0.927255     -0.939437

[200 rows x 2 columns]

In [105]:
train_features, test_features, train_labels, test_labels = train_test_split(dalseo_jangki_sc['covid_dalseo'], dalseo_jangki_sc['sales_jangki'])

In [81]:
test_features

StandardScaler()

In [110]:
train_labels

78     1.169266
19    -0.979249
45    -0.990232
65    -0.577003
52    -0.276349
         ...
61     0.386740
192   -0.909234
92    -2.803772
150   -0.393041
160   -0.231044
Name: sales_jangki, Length: 150, dtype: float64

In [108]:
model = LogisticRegression()
model.fit(train_features, train_labels)

ValueError: Expected 2D array, got 1D array instead:
array=[-0.69950815  0.38500061 -0.97063534 -0.97063534 -0.69950815  1.19838218
 -0.42838096 -0.15725377  0.6561278  -0.15725377 -0.69950815 -0.42838096
 -0.42838096 -0.15725377 -0.15725377 -0.15725377 -0.69950815  5.26529003
 -0.97063534 -0.69950815 -0.69950815  2.01176375 -0.42838096  0.11387342
 -0.97063534 -0.15725377 -0.42838096  0.11387342 -0.97063534 -0.97063534
  0.6561278  -0.97063534  0.38500061 -0.97063534  1.46950937  0.38500061
  1.46950937  0.38500061 -0.69950815 -0.15725377 -0.15725377 -0.69950815
  1.19838218 -0.69950815 -0.97063534  0.11387342  0.11387342 -0.97063534
 -0.97063534 -0.42838096 -0.69950815 -0.15725377 -0.69950815 -0.15725377
 -0.97063534  0.11387342 -0.15725377 -0.42838096 -0.15725377  3.63852689
 -0.42838096 -0.42838096  0.92725499 -0.69950815 -0.69950815 -0.97063534
  0.11387342  0.38500061  0.6561278   0.38500061  0.92725499 -0.15725377
 -0.69950815  0.11387342 -0.42838096  2.28289094  0.11387342 -0.15725377
 -0.42838096  0.92725499 -0.97063534 -0.69950815 -0.69950815 -0.97063534
 -0.69950815  0.11387342  1.19838218 -0.69950815  2.28289094 -0.97063534
  0.38500061 -0.69950815 -0.42838096  1.46950937  2.28289094 -0.42838096
 -0.69950815 -0.42838096  2.55401813  0.38500061 -0.69950815  1.46950937
  0.11387342 -0.97063534  1.46950937 -0.42838096 -0.97063534  0.6561278
  0.38500061 -0.42838096 -0.69950815  2.55401813 -0.69950815  0.11387342
 -0.69950815  0.38500061  0.11387342  2.28289094 -0.42838096 -0.97063534
  0.6561278  -0.69950815 -0.15725377  0.6561278   0.6561278  -0.97063534
  0.11387342 -0.42838096  0.92725499 -0.69950815  2.82514532  0.11387342
 -0.15725377 -0.69950815 -0.15725377 -0.69950815 -0.97063534 -0.69950815
 -0.69950815 -0.69950815 -0.69950815  3.09627251  0.11387342 -0.42838096
 -0.15725377 -0.69950815  0.92725499  1.46950937  1.74063656  1.19838218].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [79]:
model.score(train_features, train_labels)

0.08