In [1]:
import os
import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.tsa.api import VAR

#### 제가 창업한 기업에서 실제로 사용 중인 기업의 매출 데이터 입니다.

In [2]:
os.chdir(r'G:\공유 드라이브\SicParvisMagna\데이터\인공지능모델_데이터셋구축\매출데이터')
df_sales = pd.read_csv('무보까 일별 매출_모든 매장_13-10-02_21-03-31.csv')
df_sales.index = df_sales['Unnamed: 0']
del df_sales['Unnamed: 0']
df_sales

,신평,서문,성서,석적,황상,평리,구평,신서,원대,안동,서구,남김천,옥계,장기,용산,엑스코,상인
Unnamed: 0,,,,,,,,,,,,,,,,,
2013-10-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-10-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-10-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,359000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-10-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,413000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-10-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,452000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-27,1613500.0,294500.0,2605000.0,2605000.0,1613500.0,1613500.0,NaN,1613500.0,177000.0,1165500.0,714500.0,1613500.0,2190000.0,1613500.0,848000.0,295000.0,1970500.0
2021-03-28,1203000.0,274000.0,2878500.0,2878500.0,1203000.0,1203000.0,NaN,1203000.0,292000.0,617000.0,971500.0,1203000.0,2842000.0,1203000.0,1287500.0,267500.0,2075500.0
2021-03-29,889500.0,205000.0,1438000.0,1438000.0,889500.0,889500.0,117300.0,889500.0,379000.0,667000.0,697000.0,889500.0,1038500.0,889500.0,511500.0,318500.0,1742500.0
2021-03-30,1190500.0,202500.0,1719000.0,1719000.0,1190500.0,1190500.0,105000.0,1190500.0,247000.0,257500.0,532000.0,1190500.0,1784000.0,1190500.0,571500.0,207500.0,1223500.0
2021-03-31,356000.0,NaN,373000.0,373000.0,356000.0,356000.0,NaN,356000.0,14000.0,NaN,NaN,356000.0,510000.0,356000.0,NaN,NaN,403500.0

#### 여러 지점 중에 하나의 지점만 선택하여 분석할 예정입니다.

In [3]:
df_si = pd.DataFrame(df_sales['상인']).dropna()
df_si = df_si[2:]
df_si

                   상인
Unnamed: 0
2017-11-27  1203000.0
2017-11-28  1275000.0
2017-11-29  1304500.0
2017-11-30  1394000.0
2017-12-01  1238000.0
...               ...
2021-03-27  1970500.0
2021-03-28  2075500.0
2021-03-29  1742500.0
2021-03-30  1223500.0
2021-03-31   403500.0

[1191 rows x 1 columns]

#### 일별 매출과 KOSPI, 금리 간의 상관관계를 분석하고 회귀분석을 통해 일별 매출을 예측해보려고 합니다.

In [4]:
os.chdir(r'G:\공유 드라이브\SicParvisMagna\데이터\인공지능모델_데이터셋구축\경제지표')
df_koint = pd.read_csv('KOSPI_금리_휴일메꿈_2014-2021.csv', encoding = 'cp949')
df_koint.index = df_koint['Unnamed: 0']
del df_koint['Unnamed: 0']
df_koint

              KOSPI    금리
Unnamed: 0
2014-01-02  1967.19  2.78
2014-01-03  1946.14  2.78
2014-01-04  1946.14  2.78
2014-01-05  1946.14  2.78
2014-01-06  1953.28  2.77
...             ...   ...
2021-03-27  3041.01  0.89
2021-03-28  3041.01  0.89
2021-03-29  3036.04  0.89
2021-03-30  3070.00  0.89
2021-03-31  3061.42  0.89

[2643 rows x 2 columns]

In [5]:
df_si['KOSPI'] = df_koint['KOSPI']
df_si['금리'] = df_koint['금리']
df_si

                   상인    KOSPI    금리
Unnamed: 0
2017-11-27  1203000.0  2507.81  2.02
2017-11-28  1275000.0  2514.19  2.03
2017-11-29  1304500.0  2512.90  2.02
2017-11-30  1394000.0  2476.37  2.02
2017-12-01  1238000.0  2475.41  2.01
...               ...      ...   ...
2021-03-27  1970500.0  3041.01  0.89
2021-03-28  2075500.0  3041.01  0.89
2021-03-29  1742500.0  3036.04  0.89
2021-03-30  1223500.0  3070.00  0.89
2021-03-31   403500.0  3061.42  0.89

[1191 rows x 3 columns]

#### 데이터 안정화를 위해 log 를 취하거나 log 를 취하고 차분을 해줍니다.

In [6]:
df_si_log = np.log(df_si)
df_si_log = df_si_log[:-120]
df_si_log

                   상인     KOSPI        금리
Unnamed: 0
2017-11-27  14.000329  7.827165  0.703098
2017-11-28  14.058457  7.829706  0.708036
2017-11-29  14.081330  7.829193  0.703098
2017-11-30  14.147688  7.814549  0.703098
2017-12-01  14.029008  7.814161  0.698135
...               ...       ...       ...
2020-11-27  14.278301  7.876050 -0.061875
2020-11-28  14.606918  7.876050 -0.061875
2020-11-29  14.613243  7.876050 -0.061875
2020-11-30  14.181888  7.859930 -0.072571
2020-12-01  14.460780  7.876354 -0.072571

[1071 rows x 3 columns]

In [7]:
df_si_logdiff = np.log(df_si).diff().dropna()
df_si_logdiff = df_si_logdiff[:-120]
df_si_logdiff

                  상인     KOSPI        금리
Unnamed: 0
2017-11-28  0.058128  0.002541  0.004938
2017-11-29  0.022874 -0.000513 -0.004938
2017-11-30  0.066357 -0.014644  0.000000
2017-12-01 -0.118680 -0.000388 -0.004963
2017-12-02  0.035314  0.000000  0.000000
...              ...       ...       ...
2020-11-27  0.313508  0.002867  0.010695
2020-11-28  0.328617  0.000000  0.000000
2020-11-29  0.006325  0.000000  0.000000
2020-11-30 -0.431355 -0.016120 -0.010695
2020-12-01  0.278891  0.016423  0.000000

[1070 rows x 3 columns]

#### 모델은 VAR 모델을 사용하였고, aic 를 기준으로 lag order 를 설정하였습니다.

In [8]:
model = VAR(df_si_logdiff)
results_all = model.fit(maxlags = 100, ic = 'aic')
results_all.summary()

C:\Users\alswo\anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:583: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)

  Summary of Regression Results
==================================
Model:                         VAR
Method:                        OLS
Date:           Wed, 09, Jun, 2021
Time:                     12:27:48
--------------------------------------------------------------------
No. of Equations:         3.00000    BIC:                   -20.5254
Nobs:                     1050.00    HQIC:                  -21.0617
Log likelihood:           6942.71    FPE:                5.13956e-10
AIC:                     -21.3893    Det(Omega_mle):     4.33862e-10
--------------------------------------------------------------------
Results for equation 상인
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const            -0.003711         0.009039           -0.411           0.681
L1.상인            -0.749528         0.031486          -23.805           0.000
L1.KOSPI         -0.530467         0.923034           -0.575           0.565
L1.금리            -0.249312         1.200063           -0.208           0.835
L2.상인            -0.690823         0.040525          -17.047           0.000
L2.KOSPI          1.871109         0.921698            2.030           0.042
L2.금리            -0.019579         1.254405           -0.016           0.988
L3.상인            -0.616762         0.046151          -13.364           0.000
L3.KOSPI         -0.032526         0.927151           -0.035           0.972
L3.금리             0.205012         1.250713            0.164           0.870
L4.상인            -0.548928         0.050247          -10.925           0.000
L4.KOSPI          0.388837         0.921181            0.422           0.673
L4.금리            -1.631572         1.262006           -1.293           0.196
L5.상인            -0.493911         0.053040           -9.312           0.000
L5.KOSPI          0.086262         0.924494            0.093           0.926
L5.금리            -0.176805         1.265611           -0.140           0.889
L6.상인            -0.448376         0.055103           -8.137           0.000
L6.KOSPI         -1.275744         0.917331           -1.391           0.164
L6.금리            -1.898316         1.261588           -1.505           0.132
L7.상인            -0.221411         0.056815           -3.897           0.000
L7.KOSPI         -0.477846         0.915090           -0.522           0.602
L7.금리             1.916257         1.258510            1.523           0.128
L8.상인            -0.227039         0.056376           -4.027           0.000
L8.KOSPI         -0.029827         0.913348           -0.033           0.974
L8.금리             2.545956         1.254136            2.030           0.042
L9.상인            -0.298163         0.055615           -5.361           0.000
L9.KOSPI          0.125445         0.912602            0.137           0.891
L9.금리            -0.229281         1.257147           -0.182           0.855
L10.상인           -0.346001         0.055101           -6.279           0.000
L10.KOSPI        -1.169937         0.911345           -1.284           0.199
L10.금리            2.289721         1.257340            1.821           0.069
L11.상인           -0.365421         0.055031           -6.640           0.000
L11.KOSPI         0.316580         0.911661            0.347           0.728
L11.금리           -1.506489         1.258017           -1.198           0.231
L12.상인           -0.378675         0.055411           -6.834           0.000
L12.KOSPI         1.354545         0.910319            1.488           0.137
L12.금리           -2.024882         1.258138           -1.609           0.108
L13.상인           -0.312439         0.056266           -5.553           0.000
L13.KOSPI         0.885889         0.915752            0.967           0.333
L13.금리           -4.453729         1.260583           -3.533           0.000
L14.상인           -0.097113         0.056748           -1.711           0.087
L14.KOSPI        -0.041772         0.922073           -0.045           0.964
L14.금리            1.810012         1.263264            1.433           0.152
L15.상인           -0.099637         0.054886           -1.815           0.069
L15.KOSPI        -0.121952         0.921037           -0.132           0.895
L15.금리            0.619748         1.271418            0.487           0.626
L16.상인           -0.143436         0.052806           -2.716           0.007
L16.KOSPI        -1.307150         0.924186           -1.414           0.157
L16.금리            1.253229         1.278543            0.980           0.327
L17.상인           -0.140743         0.050050           -2.812           0.005
L17.KOSPI        -0.570933         0.919948           -0.621           0.535
L17.금리            1.251677         1.274490            0.982           0.326
L18.상인           -0.194953         0.046126           -4.227           0.000
L18.KOSPI        -0.295683         0.905228           -0.327           0.744
L18.금리            0.548665         1.279167            0.429           0.668
L19.상인           -0.239624         0.041035           -5.839           0.000
L19.KOSPI         0.421751         0.905857            0.466           0.642
L19.금리           -2.733918         1.278887           -2.138           0.033
L20.상인           -0.172793         0.033978           -5.085           0.000
L20.KOSPI        -0.696295         0.902088           -0.772           0.440
L20.금리           -1.686052         1.239838           -1.360           0.174
============================================================================

Results for equation KOSPI
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const             0.000023         0.000314            0.073           0.942
L1.상인             0.006001         0.001094            5.484           0.000
L1.KOSPI         -0.034889         0.032081           -1.088           0.277
L1.금리             0.167740         0.041709            4.022           0.000
L2.상인             0.002836         0.001408            2.014           0.044
L2.KOSPI          0.110144         0.032034            3.438           0.001
L2.금리            -0.001122         0.043598           -0.026           0.979
L3.상인             0.002819         0.001604            1.758           0.079
L3.KOSPI          0.061734         0.032224            1.916           0.055
L3.금리            -0.201701         0.043469           -4.640           0.000
L4.상인             0.002562         0.001746            1.467           0.142
L4.KOSPI          0.095982         0.032016            2.998           0.003
L4.금리             0.041444         0.043862            0.945           0.345
L5.상인             0.001572         0.001843            0.853           0.394
L5.KOSPI          0.013547         0.032131            0.422           0.673
L5.금리             0.017338         0.043987            0.394           0.693
L6.상인             0.001159         0.001915            0.605           0.545
L6.KOSPI         -0.024774         0.031882           -0.777           0.437
L6.금리            -0.045059         0.043847           -1.028           0.304
L7.상인             0.001251         0.001975            0.633           0.527
L7.KOSPI          0.004110         0.031805            0.129           0.897
L7.금리            -0.005456         0.043740           -0.125           0.901
L8.상인            -0.000537         0.001959           -0.274           0.784
L8.KOSPI         -0.016913         0.031744           -0.533           0.594
L8.금리            -0.073043         0.043588           -1.676           0.094
L9.상인            -0.000182         0.001933           -0.094           0.925
L9.KOSPI         -0.003230         0.031718           -0.102           0.919
L9.금리            -0.007439         0.043693           -0.170           0.865
L10.상인            0.000813         0.001915            0.425           0.671
L10.KOSPI         0.051423         0.031674            1.623           0.104
L10.금리            0.006784         0.043700            0.155           0.877
L11.상인            0.000750         0.001913            0.392           0.695
L11.KOSPI         0.011442         0.031685            0.361           0.718
L11.금리            0.027155         0.043723            0.621           0.535
L12.상인           -0.000951         0.001926           -0.494           0.621
L12.KOSPI        -0.095458         0.031639           -3.017           0.003
L12.금리            0.044501         0.043727            1.018           0.309
L13.상인            0.000181         0.001956            0.092           0.926
L13.KOSPI         0.058291         0.031828            1.831           0.067
L13.금리            0.007323         0.043812            0.167           0.867
L14.상인           -0.000535         0.001972           -0.271           0.786
L14.KOSPI        -0.020273         0.032047           -0.633           0.527
L14.금리            0.150203         0.043906            3.421           0.001
L15.상인           -0.005378         0.001908           -2.819           0.005
L15.KOSPI        -0.055306         0.032011           -1.728           0.084
L15.금리           -0.119037         0.044189           -2.694           0.007
L16.상인           -0.002076         0.001835           -1.131           0.258
L16.KOSPI        -0.015968         0.032121           -0.497           0.619
L16.금리           -0.013716         0.044437           -0.309           0.758
L17.상인           -0.000330         0.001740           -0.190           0.850
L17.KOSPI         0.007154         0.031973            0.224           0.823
L17.금리            0.158626         0.044296            3.581           0.000
L18.상인           -0.002973         0.001603           -1.855           0.064
L18.KOSPI        -0.028455         0.031462           -0.904           0.366
L18.금리           -0.016334         0.044458           -0.367           0.713
L19.상인           -0.001038         0.001426           -0.728           0.467
L19.KOSPI         0.010911         0.031484            0.347           0.729
L19.금리           -0.076461         0.044449           -1.720           0.085
L20.상인           -0.000965         0.001181           -0.817           0.414
L20.KOSPI         0.082326         0.031353            2.626           0.009
L20.금리           -0.104634         0.043091           -2.428           0.015
============================================================================

Results for equation 금리
============================================================================
               coefficient       std. error           t-stat            prob
----------------------------------------------------------------------------
const            -0.000395         0.000242           -1.631           0.103
L1.상인             0.010774         0.000843           12.783           0.000
L1.KOSPI         -0.027218         0.024709           -1.102           0.271
L1.금리             0.296444         0.032125            9.228           0.000
L2.상인             0.006438         0.001085            5.934           0.000
L2.KOSPI          0.017643         0.024673            0.715           0.475
L2.금리            -0.007149         0.033580           -0.213           0.831
L3.상인             0.005815         0.001235            4.707           0.000
L3.KOSPI         -0.001345         0.024819           -0.054           0.957
L3.금리             0.048408         0.033481            1.446           0.148
L4.상인             0.004640         0.001345            3.450           0.001
L4.KOSPI         -0.001620         0.024659           -0.066           0.948
L4.금리             0.082599         0.033783            2.445           0.014
L5.상인             0.003494         0.001420            2.461           0.014
L5.KOSPI          0.022214         0.024748            0.898           0.369
L5.금리             0.053053         0.033880            1.566           0.117
L6.상인             0.002725         0.001475            1.847           0.065
L6.KOSPI          0.013280         0.024556            0.541           0.589
L6.금리            -0.022721         0.033772           -0.673           0.501
L7.상인             0.002233         0.001521            1.468           0.142
L7.KOSPI         -0.065337         0.024496           -2.667           0.008
L7.금리             0.045566         0.033690            1.353           0.176
L8.상인            -0.001137         0.001509           -0.754           0.451
L8.KOSPI         -0.017361         0.024450           -0.710           0.478
L8.금리            -0.014226         0.033573           -0.424           0.672
L9.상인            -0.000134         0.001489           -0.090           0.928
L9.KOSPI          0.002669         0.024430            0.109           0.913
L9.금리            -0.047478         0.033653           -1.411           0.158
L10.상인            0.001620         0.001475            1.098           0.272
L10.KOSPI         0.018716         0.024396            0.767           0.443
L10.금리            0.028629         0.033658            0.851           0.395
L11.상인            0.002356         0.001473            1.599           0.110
L11.KOSPI         0.017782         0.024405            0.729           0.466
L11.금리           -0.043061         0.033676           -1.279           0.201
L12.상인            0.002817         0.001483            1.899           0.058
L12.KOSPI        -0.070128         0.024369           -2.878           0.004
L12.금리            0.062898         0.033680            1.868           0.062
L13.상인            0.002216         0.001506            1.471           0.141
L13.KOSPI        -0.080545         0.024514           -3.286           0.001
L13.금리            0.054386         0.033745            1.612           0.107
L14.상인            0.001971         0.001519            1.297           0.194
L14.KOSPI         0.010600         0.024683            0.429           0.668
L14.금리            0.029259         0.033817            0.865           0.387
L15.상인           -0.001253         0.001469           -0.853           0.394
L15.KOSPI        -0.007666         0.024656           -0.311           0.756
L15.금리           -0.089511         0.034035           -2.630           0.009
L16.상인            0.000937         0.001414            0.663           0.508
L16.KOSPI         0.029193         0.024740            1.180           0.238
L16.금리            0.030205         0.034226            0.883           0.377
L17.상인            0.000497         0.001340            0.371           0.711
L17.KOSPI         0.027133         0.024626            1.102           0.271
L17.금리           -0.040810         0.034117           -1.196           0.232
L18.상인           -0.001262         0.001235           -1.022           0.307
L18.KOSPI         0.051817         0.024232            2.138           0.032
L18.금리           -0.034265         0.034243           -1.001           0.317
L19.상인           -0.000828         0.001098           -0.754           0.451
L19.KOSPI         0.006386         0.024249            0.263           0.792
L19.금리           -0.025120         0.034235           -0.734           0.463
L20.상인            0.000747         0.000910            0.821           0.412
L20.KOSPI         0.057741         0.024148            2.391           0.017
L20.금리            0.025067         0.033190            0.755           0.450
============================================================================

Correlation matrix of residuals
               상인     KOSPI        금리
상인       1.000000 -0.037720 -0.054114
KOSPI   -0.037720  1.000000  0.155010
금리      -0.054114  0.155010  1.000000

#### VAR 모델을 통해 나온 식으로 120일 까지를 예측해 보았습니다.

In [9]:
np_forc_120 = results_all.forecast(df_si_logdiff.values[-results_all.k_ar : ], 120)
np_forc_120

array([[-3.11175354e-01, -1.66736987e-03,  4.83631321e-03],
       [-3.03147926e-02,  1.70303982e-05, -1.36781628e-03],
       [ 2.67468261e-01, -3.10398438e-03, -4.70625804e-04],
       [ 3.90191621e-01, -1.21838648e-03, -3.28218686e-03],
       [-6.21975073e-02,  4.46908556e-03,  4.57434063e-04],
       [-5.06202467e-01,  1.12001167e-03,  2.92342428e-03],
       [-1.37080296e-01,  4.62711269e-03,  2.26240901e-04],
       [-9.85729801e-03, -3.96987081e-04, -3.44314945e-03],
       [-6.84569351e-03, -3.49886979e-03, -3.04442115e-03],
       [ 3.23155864e-01,  3.11925074e-03,  3.64793562e-04],
       [ 3.20028153e-01,  2.63425437e-03,  1.00524492e-03],
       [-5.85987286e-02, -7.62272469e-05,  1.17422379e-04],
       [-4.28137056e-01,  2.43937397e-04, -4.15103516e-04],
       [-9.92092544e-02, -2.90383658e-04,  9.76317069e-05],
       [-3.71154766e-02, -2.09045370e-03, -2.43610345e-03],
       [-3.30674751e-02, -4.91720687e-03, -7.94971084e-04],
       [ 2.96243969e-01,  8.87052441e-04, -1.96679341e-03],
       [ 2.66250331e-01, -2.75215234e-04, -1.48003591e-03],
       [-2.01020804e-02, -1.34959692e-03, -2.07580159e-03],
       [-3.43019357e-01,  1.55907013e-03,  8.88933387e-04],
       [-7.37903621e-02,  1.43599816e-03, -2.12456609e-04],
       [-5.70607159e-02, -4.56666939e-04, -1.16897586e-03],
       [ 1.10536930e-02, -1.15531272e-03, -1.63567176e-03],
       [ 2.50786528e-01,  1.57962190e-03, -7.84486979e-04],
       [ 2.44021390e-01, -2.00866170e-04, -1.95353188e-04],
       [-5.05805993e-02, -1.23240420e-03,  3.94050991e-04],
       [-3.01399163e-01,  1.71626306e-03,  9.98177440e-04],
       [-1.11909519e-01,  2.30079964e-03,  2.68263956e-04],
       [-4.85868871e-02, -1.38754793e-03, -1.65314476e-03],
       [ 2.29036164e-02, -8.12880836e-04, -1.51360819e-03],
       [ 2.22569469e-01,  8.00776597e-04, -8.56892676e-04],
       [ 2.36825734e-01, -2.26761800e-04, -6.06402506e-04],
       [-6.32763327e-02, -4.11891376e-04,  7.47179677e-06],
       [-2.42485832e-01,  9.96614357e-04,  2.73981707e-04],
       [-1.10108441e-01,  7.68881705e-04, -5.88067427e-04],
       [-3.92185783e-02, -1.61511732e-03, -1.83488614e-03],
       [ 1.45661302e-02, -4.00076410e-04, -1.62817556e-03],
       [ 2.00998571e-01,  6.55047346e-04, -9.39181975e-04],
       [ 1.96617611e-01, -3.34811511e-04, -7.95103971e-04],
       [-4.83517947e-02, -4.25676157e-04, -2.96192862e-04],
       [-2.06822721e-01,  1.07304103e-03,  1.43779327e-04],
       [-1.01012699e-01,  1.00545276e-03, -4.23348607e-04],
       [-4.65141003e-02, -5.56377035e-04, -1.48717810e-03],
       [ 1.99182587e-02, -2.68392867e-04, -1.46444036e-03],
       [ 1.83461183e-01,  3.40450675e-04, -1.00940632e-03],
       [ 1.77189444e-01, -5.08146838e-04, -6.14747876e-04],
       [-4.54142013e-02, -1.97767957e-04, -8.18952774e-05],
       [-1.80100102e-01,  9.62462727e-04,  3.22572974e-04],
       [-9.82715583e-02,  6.28034650e-04, -5.01144069e-04],
       [-4.64876402e-02, -5.45464274e-04, -1.46599615e-03],
       [ 2.23358538e-02, -3.56126414e-04, -1.44992581e-03],
       [ 1.65501318e-01,  2.04726247e-04, -9.71111977e-04],
       [ 1.55383205e-01, -3.36218361e-04, -6.32152003e-04],
       [-3.86342648e-02, -1.41483102e-04, -1.96964412e-04],
       [-1.51278387e-01,  7.93548274e-04,  4.62367706e-05],
       [-9.19403945e-02,  5.40562500e-04, -5.71863025e-04],
       [-4.73737253e-02, -3.76957848e-04, -1.31461950e-03],
       [ 2.18647127e-02, -2.54394596e-04, -1.28117764e-03],
       [ 1.47886542e-01,  1.69515559e-04, -9.28851080e-04],
       [ 1.36186081e-01, -2.40256260e-04, -6.30189715e-04],
       [-3.26140886e-02, -7.60727519e-05, -2.04451250e-04],
       [-1.29562425e-01,  7.13136635e-04,  1.16429615e-05],
       [-8.73728673e-02,  5.47976364e-04, -5.49688441e-04],
       [-4.64698774e-02, -2.64244880e-04, -1.23235834e-03],
       [ 2.21502756e-02, -1.94045081e-04, -1.25607846e-03],
       [ 1.33413268e-01,  7.39319431e-05, -9.49275751e-04],
       [ 1.20217584e-01, -2.43191364e-04, -6.48298620e-04],
       [-2.65443167e-02, -7.84675165e-05, -2.43259482e-04],
       [-1.11751218e-01,  6.16354397e-04, -8.39543575e-05],
       [-8.21986150e-02,  4.67256567e-04, -5.80533945e-04],
       [-4.52627492e-02, -2.32950005e-04, -1.17694982e-03],
       [ 2.17601087e-02, -1.77091155e-04, -1.21138105e-03],
       [ 1.19412826e-01,  5.01776322e-05, -9.46157902e-04],
       [ 1.06209605e-01, -1.93646342e-04, -6.62516705e-04],
       [-2.11018591e-02, -1.56470067e-05, -2.93466582e-04],
       [-9.62646783e-02,  5.62318520e-04, -1.62108497e-04],
       [-7.66400897e-02,  4.06193758e-04, -5.93361311e-04],
       [-4.34563744e-02, -1.75264720e-04, -1.10173853e-03],
       [ 2.05532481e-02, -1.28437889e-04, -1.14328525e-03],
       [ 1.06696137e-01,  3.44065141e-05, -9.22602236e-04],
       [ 9.38739681e-02, -1.80523206e-04, -6.61325222e-04],
       [-1.63661330e-02, -7.40341818e-07, -3.27750206e-04],
       [-8.34641769e-02,  5.01215080e-04, -2.14583455e-04],
       [-7.12378017e-02,  3.59010736e-04, -5.97210580e-04],
       [-4.14002035e-02, -1.23312453e-04, -1.04737023e-03],
       [ 1.93990502e-02, -1.01459768e-04, -1.10546410e-03],
       [ 9.55449278e-02,  7.69431121e-06, -9.21658063e-04],
       [ 8.34072841e-02, -1.63284936e-04, -6.73853702e-04],
       [-1.24076022e-02,  2.36107093e-05, -3.63596450e-04],
       [-7.25685671e-02,  4.46794806e-04, -2.66916054e-04],
       [-6.59901792e-02,  3.13058699e-04, -6.05913153e-04],
       [-3.91637061e-02, -8.58406278e-05, -1.00120074e-03],
       [ 1.79679691e-02, -7.27193398e-05, -1.06276233e-03],
       [ 8.53031276e-02, -2.16344290e-06, -9.06834792e-04],
       [ 7.41399784e-02, -1.34194798e-04, -6.77719916e-04],
       [-9.05389019e-03,  4.63006374e-05, -3.96142135e-04],
       [-6.30878326e-02,  4.00418728e-04, -3.15105568e-04],
       [-6.08971994e-02,  2.78916555e-04, -6.12123753e-04],
       [-3.68402321e-02, -5.25033907e-05, -9.58931942e-04],
       [ 1.64529727e-02, -5.20014073e-05, -1.02532299e-03],
       [ 7.61408276e-02, -1.41854986e-05, -8.96001587e-04],
       [ 6.60294072e-02, -1.16459575e-04, -6.84338708e-04],
       [-6.28192581e-03,  5.58609916e-05, -4.26440902e-04],
       [-5.49928170e-02,  3.55280771e-04, -3.56762396e-04],
       [-5.60712051e-02,  2.49982841e-04, -6.18299686e-04],
       [-3.44705728e-02, -2.48925553e-05, -9.25187120e-04],
       [ 1.49798077e-02, -3.47879452e-05, -9.94503749e-04],
       [ 6.79463574e-02, -1.90956086e-05, -8.85904955e-04],
       [ 5.89243115e-02, -9.67962817e-05, -6.89496666e-04],
       [-3.97512111e-03,  6.50976577e-05, -4.54102675e-04],
       [-4.80026186e-02,  3.17924667e-04, -3.93408856e-04],
       [-5.15093713e-02,  2.26545113e-04, -6.23055466e-04],
       [-3.21414292e-02, -2.92851576e-06, -8.94014506e-04],
       [ 1.35046929e-02, -2.11945587e-05, -9.64444374e-04],
       [ 6.05557558e-02, -2.04468440e-05, -8.73336458e-04],
       [ 5.26511794e-02, -7.86361381e-05, -6.92789797e-04],
       [-2.08294699e-03,  7.14705686e-05, -4.79173561e-04],
       [-4.19373052e-02,  2.85227751e-04, -4.26270234e-04],
       [-4.72031752e-02,  2.06670451e-04, -6.27887584e-04],
       [-2.98530210e-02,  1.47464406e-05, -8.67915814e-04]])

In [10]:
df_forc_120 = pd.DataFrame(np_forc_120)
df_forc_120.columns = ['상인', 'KOSPI', '금리']
df_forc_120

           상인     KOSPI        금리
0   -0.311175 -0.001667  0.004836
1   -0.030315  0.000017 -0.001368
2    0.267468 -0.003104 -0.000471
3    0.390192 -0.001218 -0.003282
4   -0.062198  0.004469  0.000457
..        ...       ...       ...
115  0.052651 -0.000079 -0.000693
116 -0.002083  0.000071 -0.000479
117 -0.041937  0.000285 -0.000426
118 -0.047203  0.000207 -0.000628
119 -0.029853  0.000015 -0.000868

[120 rows x 3 columns]

In [11]:
14.460780	7.876354	-0.072571

SyntaxError: invalid syntax (<ipython-input-11-90dc994e28b7>, line 1)

#### log 와 차분을 해줬기 때문에 다시 데이터를 원본으로 돌리는 과정을 거칩니다.

In [12]:
sales = 14.460780
sales_list = []
for c in df_forc_120['상인'] :
    sales += c
    sales_list.append(sales)

kos = 7.876354
kos_list = []
for b in df_forc_120['KOSPI'] :
    kos += b
    kos_list.append(kos)
    
intr = -0.072571
intr_list = []
for a in df_forc_120['금리'] :
    intr += a
    intr_list.append(intr)

In [13]:
results_forc_120 = pd.DataFrame()
results_forc_120['상인'] = sales_list
results_forc_120['KOSPI'] = kos_list
results_forc_120['금리'] = intr_list
results_forc_120

            상인     KOSPI        금리
0    14.149605  7.874687 -0.067735
1    14.119290  7.874704 -0.069103
2    14.386758  7.871600 -0.069573
3    14.776950  7.870381 -0.072855
4    14.714752  7.874850 -0.072398
..         ...       ...       ...
115  14.358720  7.883619 -0.148773
116  14.356637  7.883690 -0.149253
117  14.314699  7.883975 -0.149679
118  14.267496  7.884182 -0.150307
119  14.237643  7.884197 -0.151175

[120 rows x 3 columns]

In [14]:
np.exp(results_forc_120)

               상인        KOSPI        금리
0    1.396675e+06  2629.861942  0.934508
1    1.354970e+06  2629.906730  0.933231
2    1.770474e+06  2621.756196  0.932792
3    2.615458e+06  2618.563829  0.929735
4    2.457739e+06  2630.292604  0.930161
..            ...          ...       ...
115  1.721522e+06  2653.456904  0.861764
116  1.717940e+06  2653.646555  0.861352
117  1.647384e+06  2654.403557  0.860984
118  1.571429e+06  2654.952200  0.860444
119  1.525211e+06  2654.991352  0.859698

[120 rows x 3 columns]

#### 실제값과 예측값을 비교합니다.

In [15]:
results_120 = pd.DataFrame(df_si['상인'][-120:])
results_120 = results_120.reset_index()
results_120['예측값'] = np.exp(results_forc_120)['상인']
results_120.index = results_120['Unnamed: 0']
del results_120['Unnamed: 0']
results_120

                   상인           예측값
Unnamed: 0
2020-12-02  1495000.0  1.396675e+06
2020-12-03  1488000.0  1.354970e+06
2020-12-04  1327500.0  1.770474e+06
2020-12-05  2312000.0  2.615458e+06
2020-12-06  2463000.0  2.457739e+06
...               ...           ...
2021-03-27  1970500.0  1.721522e+06
2021-03-28  2075500.0  1.717940e+06
2021-03-29  1742500.0  1.647384e+06
2021-03-30  1223500.0  1.571429e+06
2021-03-31   403500.0  1.525211e+06

[120 rows x 2 columns]

#### 120일을 예측한 결과

In [16]:
results_120['오차제곱근'] = [((a - b)**2)**0.5 for a, b in zip(results_120['상인'], results_120['예측값'])]
results_120['오차비율'] = [d / c for c, d in zip(results_120['상인'], results_120['오차제곱근'])]
results_120

                   상인           예측값         오차제곱근      오차비율
Unnamed: 0
2020-12-02  1495000.0  1.396675e+06  9.832545e+04  0.065770
2020-12-03  1488000.0  1.354970e+06  1.330300e+05  0.089402
2020-12-04  1327500.0  1.770474e+06  4.429744e+05  0.333691
2020-12-05  2312000.0  2.615458e+06  3.034579e+05  0.131253
2020-12-06  2463000.0  2.457739e+06  5.261374e+03  0.002136
...               ...           ...           ...       ...
2021-03-27  1970500.0  1.721522e+06  2.489775e+05  0.126352
2021-03-28  2075500.0  1.717940e+06  3.575596e+05  0.172276
2021-03-29  1742500.0  1.647384e+06  9.511563e+04  0.054586
2021-03-30  1223500.0  1.571429e+06  3.479294e+05  0.284372
2021-03-31   403500.0  1.525211e+06  1.121711e+06  2.779952

[120 rows x 4 columns]

In [19]:
os.chdir(r'C:\Users\alswo\Desktop\4학년\빅데이터')
results_120.to_csv('상인_120일_매출예측.csv', encoding = 'cp949')

#### '오차제곱근 / 실제매출' 방식으로 오차비율을 구했고, 120일의 평균은 약 58.8%의 비율을 보이고 있기 때문에 성능이 아주 떨어지는 모델이라는 결론을 갖게 되었습니다. 아무래도 120일이라는 기간이 너무 길다 보니 이런 결과가 나온것 같은데, 처음 5일 정도를 예측했을 때는 10%대의 오차비율을 가졌습니다. 그리고 KOSPI 와 시장금리가 매출을 예측하는데에 크게 도움이 되지 않아서 모델 성능이 안좋을 수도 있겠다는 생각이 들었습니다. 그래서 기온, 습도, 풍속과 같은 날씨 데이터를 변수로 추가할 계획입니다. 또 한가지는 예측하는 일수를 조금 줄여볼 생각입니다.

#### 원래는 이 VAR 모델의 회귀식을 이용해서 예측을 하려던 것이 아니었습니다. VAR 모델로는 매출이라는 변수와 Coefficient 가 가장 높은 시차를 가진 변수를 LSTM 에 학습시킬 때 활용하려고 했었습니다. 예를 들어 t 시간의 매출과 가장 Coefficient 가 높은 시간대의 변수는 KOSPI(t-3) 이고 시장금리(t-5) 라고 가정했을 때, LSTM 학습 시계열 데이터를 KOSPI는 3만큼의 시차를 두고 시장금리는 5만큼의 시차를 둔 데이터를 학습시키려고 하고있습니다. 이와 관련해서 교수님의 의견이 궁금합니다.